/*
 * lib/data.ts — CHOQUE demo dataset.
 * Why: the product brief calls for a no-database demo build, so the entire
 * community directory (gyms, partners, open mats) lives here as curated,
 * realistic content with real photography from Pexels. User-generated content
 * (notebook entries, RSVPs, roll requests) is NOT here — it is created at
 * runtime and persisted to localStorage (see lib/storage.ts), so the app never
 * ships with fake user data.
 */
import type { Gym, OpenMat, Partner } from "./types";

/* Stock photography (Pexels) — landscape crops sized for cards/hero use. */
const px = (id: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200`;

const IMG = {
  hero: px(11391978), // wide mat room, athletes training
  bjjComp: px(38678708),
  bjjWomen: px(20182272),
  bjjWomen2: px(38678646),
  mmaDrill: px(38758877),
  bjjMatch: px(38678753),
  bjjTop: px(38678683),
  bjjPair: px(8612032),
  bjjKids: px(7988779),
  bjjClose: px(38678637),
  judoFace: px(6765107),
  grappleLight: px(8611380),
  judoArm: px(6765026),
  judoKids: px(7988830),
  judoGroup: px(6765108),
  judoBright: px(8612046),
  judoWomen: px(8612017),
  mtBag: px(23109960),
  mtSpar: px(23531688),
  boxingGym: px(11392385),
  kbRing: px(8611942),
  mtSmoke: px(39969614),
  mtTechnique: px(23229123),
  kbSpar: px(17474771),
  mtIntense: px(23531700),
} as const;

export const HERO_IMAGE = IMG.hero;

export const GYMS: Gym[] = [
  {
    id: "g-clash",
    slug: "clash-grappling-co",
    name: "Clash Grappling Co.",
    city: "Los Angeles",
    state: "CA",
    address: "4419 Eagle Rock Blvd, Los Angeles, CA 90041",
    disciplines: ["bjj", "nogi"],
    rating: 4.9,
    reviews: 212,
    priceFrom: 185,
    dropIn: 30,
      website: "https://clashgrappling.example.com",
  instagram: "clashgrappling",
  email: "hello@clashgrappling.example.com",
  headCoach: "Renan Vasconcelos",
    coaches: ["Renan Vasconcelos", "April Duarte", "Kev Son"],
    image: IMG.bjjPair,
    gallery: [IMG.bjjComp, IMG.bjjTop, IMG.hero],
    about:
      "A glass-walled grappling studio in Northeast LA. Deep competition bench, but fundamentals stay king — every night starts with 20 minutes of positional drilling before rounds. Visitors roll free their first week.",
    amenities: ["Showers", "Sauna", "Strength room", "Free visitor week"],
    womenOnly: false,
    kids: true,
    verified: true,
    affiliate: true,
    schedule: [
      { day: "Mon", time: "06:30", label: "Competition class", discipline: "bjj" },
      { day: "Mon", time: "19:00", label: "Fundamentals + rounds", discipline: "bjj" },
      { day: "Wed", time: "18:00", label: "No-gi all levels", discipline: "nogi" },
      { day: "Fri", time: "19:00", label: "Shark tank", discipline: "bjj", openMat: true },
      { day: "Sat", time: "10:00", label: "Open mat", discipline: "bjj", openMat: true },
    ],
  },
  {
    id: "g-nine-clouds",
    slug: "nine-clouds-jiu-jitsu",
    name: "Nine Clouds Jiu-Jitsu",
    city: "San Diego",
    state: "CA",
    address: "2810 El Cajon Blvd, San Diego, CA 92104",
    disciplines: ["bjj", "judo"],
    rating: 4.8,
    reviews: 164,
    priceFrom: 170,
    dropIn: 25,
      website: "https://ninecloudsbjj.example.com",
  instagram: "ninecloudsbjj",
  email: "front@ninecloudsbjj.example.com",
  headCoach: "Marcelo Assunção",
    coaches: ["Marcelo Assunção", "Dana Reyes"],
    image: IMG.bjjWomen,
    gallery: [IMG.bjjWomen2, IMG.bjjMatch, IMG.judoFace],
    about:
      "Old-school mat room with new-school programming. Gi in the mornings, judo on Tuesdays, and the friendliest women's program in San Diego. Home to three IBJJF world medalists.",
    amenities: ["Showers", "Women's program", "Gi rental"],
    womenOnly: true,
    kids: true,
    verified: true,
    affiliate: true,
    schedule: [
      { day: "Tue", time: "07:00", label: "Gi all levels", discipline: "bjj" },
      { day: "Tue", time: "19:00", label: "Judo standing + ne-waza", discipline: "judo" },
      { day: "Thu", time: "19:00", label: "Competition class", discipline: "bjj" },
      { day: "Sat", time: "11:00", label: "Women's open mat", discipline: "bjj", openMat: true },
      { day: "Sun", time: "10:00", label: "Open mat", discipline: "bjj", openMat: true },
    ],
  },
  {
    id: "g-harbor",
    slug: "harbor-judo-club",
    name: "Harbor Judo Club",
    city: "Seattle",
    state: "WA",
    address: "911 N 98th St, Seattle, WA 98103",
    disciplines: ["judo"],
    rating: 4.7,
    reviews: 98,
    priceFrom: 95,
    dropIn: 15,
      website: "",
  instagram: "harborjudoseattle",
  email: "info@harborjudo.example.com",
  headCoach: "Akira Onishi",
    coaches: ["Akira Onishi", "Petra Balcik"],
    image: IMG.judoFace,
    gallery: [IMG.judoGroup, IMG.judoWomen, IMG.judoBright],
    about:
      "A non-profit judo club running since 1978. Technical randori-first sessions, monthly kata clinics, and spring floors that forgive even the sloppiest uchi-komi. All ranks welcome, always.",
    amenities: ["Sprung floors", "Non-profit dues", "Beginner course"],
    womenOnly: false,
    kids: true,
    verified: true,
    affiliate: false,
    schedule: [
      { day: "Mon", time: "18:30", label: "Technical randori", discipline: "judo" },
      { day: "Wed", time: "18:30", label: "Competition randori", discipline: "judo" },
      { day: "Fri", time: "19:00", label: "Kata + ne-waza clinic", discipline: "judo" },
      { day: "Sat", time: "12:00", label: "Open mat", discipline: "judo", openMat: true },
    ],
  },
  {
    id: "g-boiler",
    slug: "boiler-room-wrestling",
    name: "Boiler Room Wrestling",
    city: "Denver",
    state: "CO",
    address: "3770 Jason St, Denver, CO 80211",
    disciplines: ["wrestling", "nogi"],
    rating: 4.8,
    reviews: 121,
    priceFrom: 120,
    dropIn: 20,
      website: "",
  instagram: "boilerroomwrestling",
  email: "coach@boilerroom.example.com",
  headCoach: "Dan Petrosyan",
    coaches: ["Dan Petrosyan", "Kwame Asante"],
    image: IMG.grappleLight,
    gallery: [IMG.judoArm, IMG.mmaDrill, IMG.kbSpar],
    about:
      "Folkstyle and freestyle wrestling for adults who found the sport late — and for MMA fighters who need a real shot-defense hour. Two rooms, 2,400 sq ft of fresh Matflex, altitude lungs included.",
    amenities: ["Two mat rooms", "Open drilling hours", "Altitude training"],
    womenOnly: false,
    kids: false,
    verified: false,
    affiliate: false,
    schedule: [
      { day: "Tue", time: "06:00", label: "Freestyle practice", discipline: "wrestling" },
      { day: "Thu", time: "18:30", label: "Folkstyle + live goes", discipline: "wrestling" },
      { day: "Fri", time: "17:30", label: "MMA grappling", discipline: "mma" },
      { day: "Sun", time: "09:30", label: "Open mat", discipline: "wrestling", openMat: true },
    ],
  },
  {
    id: "g-cinder",
    slug: "cinder-combat-club",
    name: "Cinder Combat Club",
    city: "Austin",
    state: "TX",
    address: "507 Calles St, Austin, TX 78702",
    disciplines: ["mma", "nogi", "bjj"],
    rating: 4.9,
    reviews: 187,
    priceFrom: 195,
    dropIn: 30,
      website: "https://cindercombat.example.com",
  instagram: "cindercombat",
  email: "mat@cindercombat.example.com",
  headCoach: "Val Ospina",
    coaches: ["Val Ospina", "Theo Marsh", "Ika Putri"],
    image: IMG.mmaDrill,
    gallery: [IMG.bjjPair, IMG.mtIntense, IMG.bjjKids],
    about:
      "East Austin's quiet killer of an MMA room. Small classes, pads and cage wall in the back, and a coaching staff that cornered 14 pro fights last year. Beginners get their own lane — never thrown to the wolves.",
    amenities: ["Cage wall", "Pad room", "Showers", "Beginner lane"],
    womenOnly: false,
    kids: true,
    verified: true,
    affiliate: false,
    schedule: [
      { day: "Mon", time: "18:00", label: "MMA fundamentals", discipline: "mma" },
      { day: "Wed", time: "19:00", label: "Pro/am sparring (invite)", discipline: "mma" },
      { day: "Thu", time: "18:00", label: "No-gi grappling", discipline: "nogi" },
      { day: "Sat", time: "12:00", label: "Open mat", discipline: "mma", openMat: true },
    ],
  },
  {
    id: "g-golden-hour",
    slug: "golden-hour-muay-thai",
    name: "Golden Hour Muay Thai",
    city: "Miami",
    state: "FL",
    address: "2234 NW 2nd Ave, Miami, FL 33127",
    disciplines: ["striking", "mma"],
    rating: 4.8,
    reviews: 143,
    priceFrom: 150,
    dropIn: 25,
      website: "https://goldenhourmt.example.com",
  instagram: "goldenhourmuaythai",
  email: "gym@goldenhourmt.example.com",
  headCoach: "Kwan Sitmonchai",
    coaches: ["Kwan Sitmonchai", "Rosa Medina"],
    image: IMG.mtSmoke,
    gallery: [IMG.mtBag, IMG.mtSpar, IMG.mtTechnique],
    about:
      "Clinch-heavy, Bangkok-style rounds in a Wynwood warehouse. Morning conditioning is brutal and beautiful; evening technical sparring stays light enough to train the next day. Long bag line, cold AC.",
    amenities: ["16 bags", "Two rings", "Conditioning floor"],
    womenOnly: false,
    kids: false,
    verified: true,
    affiliate: false,
    schedule: [
      { day: "Mon", time: "06:00", label: "Conditioning + bag", discipline: "striking" },
      { day: "Wed", time: "18:30", label: "Technical sparring", discipline: "striking" },
      { day: "Fri", time: "18:30", label: "Clinch rounds", discipline: "striking" },
      { day: "Sun", time: "10:30", label: "Open mat + pads", discipline: "striking", openMat: true },
    ],
  },
  {
    id: "g-north-star",
    slug: "north-star-boxing",
    name: "North Star Boxing",
    city: "Chicago",
    state: "IL",
    address: "1843 W Hubbard St, Chicago, IL 60622",
    disciplines: ["striking"],
    rating: 4.7,
    reviews: 89,
    priceFrom: 110,
    dropIn: 20,
      website: "",
  instagram: "northstarboxing",
  email: "ring@northstarboxing.example.com",
  headCoach: "Eddie Kaczmarek",
    coaches: ["Eddie Kaczmarek", "Tanya Bell"],
    image: IMG.boxingGym,
    gallery: [IMG.mtTechnique, IMG.kbRing, IMG.kbSpar],
    about:
      "A West Town boxing gym with old walls and new ideas. Defense-first curriculum, mitt work every session, and a Tuesday night smoker series for fighters building toward the Golden Gloves.",
    amenities: ["Two rings", "Mitt work every class", "Smoker nights"],
    womenOnly: false,
    kids: true,
    verified: false,
    affiliate: false,
    schedule: [
      { day: "Tue", time: "18:00", label: "Fighter's hour", discipline: "striking" },
      { day: "Thu", time: "18:00", label: "All levels boxing", discipline: "striking" },
      { day: "Sat", time: "09:00", label: "Open ring + bags", discipline: "striking", openMat: true },
    ],
  },
  {
    id: "g-flatline",
    slug: "flatline-bjj",
    name: "Flatline BJJ",
    city: "Portland",
    state: "OR",
    address: "2218 SE Ankeny St, Portland, OR 97214",
    disciplines: ["bjj", "nogi"],
    rating: 4.9,
    reviews: 176,
    priceFrom: 165,
    dropIn: 25,
      website: "https://flatlinebjj.example.com",
  instagram: "flatlinebjj",
  email: "frontdesk@flatlinebjj.example.com",
  headCoach: "Beatriz Fontoura",
    coaches: ["Beatriz Fontoura", "Hank Ellison"],
    image: IMG.bjjTop,
    gallery: [IMG.bjjClose, IMG.bjjComp, IMG.hero],
    about:
      "Heavylegs-style pressure passing and leglock-literate no-gi in inner SE. The 6 am crew is legendary, the playlist is not — bring your own headphones for the warm-up laps.",
    amenities: ["6 am crew", "Showers", "Leglock-literate"],
    womenOnly: true,
    kids: false,
    verified: true,
    affiliate: true,
    schedule: [
      { day: "Mon", time: "06:00", label: "Gi early birds", discipline: "bjj" },
      { day: "Wed", time: "18:30", label: "No-gi all levels", discipline: "nogi" },
      { day: "Thu", time: "18:30", label: "Competition rounds", discipline: "bjj" },
      { day: "Sat", time: "13:00", label: "Open mat", discipline: "nogi", openMat: true },
    ],
  },
  {
    id: "g-anchor-arm",
    slug: "anchor-and-arm",
    name: "Anchor & Arm",
    city: "New York",
    state: "NY",
    address: "550 Grand St, Brooklyn, NY 11211",
    disciplines: ["judo", "bjj", "wrestling"],
    rating: 4.8,
    reviews: 231,
    priceFrom: 210,
    dropIn: 35,
      website: "https://anchorandarm.example.com",
  instagram: "anchorandarm",
  email: "front@anchorandarm.example.com",
  headCoach: "Levan Kiknadze",
    coaches: ["Levan Kiknadze", "Maya Cohen", "Bruno Tavares"],
    image: IMG.judoBright,
    gallery: [IMG.judoArm, IMG.judoFace, IMG.bjjMatch],
    about:
      "Throws on Tuesdays, guard on Thursdays, grip fighting always. A judo-first room in Williamsburg where BJJ folks come to fix their stand-up and judoka come to survive the ground. Serious, kind, crowded.",
    amenities: ["Tatami + flexi-roll", "Showers", "Grip clinic monthly"],
    womenOnly: false,
    kids: true,
    verified: true,
    affiliate: false,
    schedule: [
      { day: "Tue", time: "19:00", label: "Judo + tachi-waza", discipline: "judo" },
      { day: "Thu", time: "19:00", label: "BJJ all levels", discipline: "bjj" },
      { day: "Fri", time: "18:00", label: "Greco hour", discipline: "wrestling" },
      { day: "Sun", time: "11:00", label: "Open mat", discipline: "bjj", openMat: true },
    ],
  },
  {
    id: "g-cerro",
    slug: "cerro-striking-and-mma",
    name: "Cerro Striking & MMA",
    city: "San Francisco",
    state: "CA",
    address: "3145 24th St, San Francisco, CA 94110",
    disciplines: ["mma", "striking"],
    rating: 4.7,
    reviews: 112,
    priceFrom: 175,
    dropIn: 25,
      website: "",
  instagram: "cerrostriking",
  email: "sparr@cerrostriking.example.com",
  headCoach: "Pilár Andrade",
    coaches: ["Pilár Andrade", "Junior Santos"],
    image: IMG.mtIntense,
    gallery: [IMG.kbRing, IMG.mmaDrill, IMG.mtBag],
    about:
      "Mission District striking lab. Dutch-style kickboxing rounds, wall-and-cage wrestling on Wednesdays, and an amateur fight team that actually teaches instead of gatekeeping. Cleanest mats in the city, allegedly.",
    amenities: ["Cage wall", "Video review nights", "Showers"],
    womenOnly: true,
    kids: false,
    verified: true,
    affiliate: false,
    schedule: [
      { day: "Mon", time: "18:00", label: "Kickboxing rounds", discipline: "striking" },
      { day: "Wed", time: "18:00", label: "Wall + cage wrestling", discipline: "mma" },
      { day: "Fri", time: "17:30", label: "Fight team sparring", discipline: "mma" },
      { day: "Sat", time: "10:00", label: "Open mat", discipline: "mma", openMat: true },
    ],
  },
];

export const PARTNERS: Partner[] = [
  {
    id: "p-ana",
    slug: "ana-ribeiro",
    name: "Ana Ribeiro",
    city: "Los Angeles", state: "CA",
    homeGymId: "g-clash",
    disciplines: ["bjj", "nogi"], primaryDiscipline: "bjj",
    rank: "BJJ purple belt", beltColor: "#6D28D9", stripes: 1,
    yearsTraining: 6, weightKg: 63,
    availability: ["Morning", "Midday"], weekdays: ["Mon", "Wed", "Sat"],
    lookingFor: ["Drilling", "Comp prep"],
    bio: "Mundials scheduled for June — looking for small, focused drilling groups. Half-guard, knee cut, and cardio forever. Happy to pace for bigger partners.",
    lastActiveDays: 0, verified: true,
  },
  {
    id: "p-marcus",
    slug: "marcus-webb",
    name: "Marcus Webb",
    city: "Austin", state: "TX",
    homeGymId: "g-cinder",
    disciplines: ["mma", "nogi"], primaryDiscipline: "mma",
    rank: "Amateur MMA (6–2, welterweight)",
    yearsTraining: 5, weightKg: 77,
    availability: ["Evening"], weekdays: ["Tue", "Thu", "Sat"],
    lookingFor: ["Open mat", "Comp prep"],
    bio: "Fight booked in eight weeks. Need southpaw looks and anyone who can wrestle me into the cage. I will 100% bring you coffee after.",
    lastActiveDays: 1, verified: true,
  },
  {
    id: "p-yuki",
    slug: "yuki-tanabe",
    name: "Yuki Tanabe",
    city: "Seattle", state: "WA",
    homeGymId: "g-harbor",
    disciplines: ["judo"], primaryDiscipline: "judo",
    rank: "Judo nidan", beltColor: "#1C1917",
    yearsTraining: 14, weightKg: 73,
    availability: ["Midday", "Evening"], weekdays: ["Mon", "Fri"],
    lookingFor: ["Drilling", "Open mat"],
    bio: "Happy to do uchi-komi reps until your grip gives out. Working seoi-nage entries against lefties. Beginners welcome — I'll take any fall to teach.",
    lastActiveDays: 2, verified: true,
  },
  {
    id: "p-sofia",
    slug: "sofia-marchetti",
    name: "Sofia Marchetti",
    city: "San Diego", state: "CA",
    homeGymId: "g-nine-clouds",
    disciplines: ["bjj", "judo"], primaryDiscipline: "bjj",
    rank: "BJJ blue belt", beltColor: "#2563EB", stripes: 3,
    yearsTraining: 3, weightKg: 58,
    availability: ["Morning"], weekdays: ["Tue", "Thu", "Sun"],
    lookingFor: ["Beginner friendly", "Drilling"],
    bio: "Two years in and obsessed with escape mechanics. Looking for patient partners around my weight for positional rounds. I narrate what I'm feeling — great for troubleshooting your pressure.",
    lastActiveDays: 0, verified: true,
  },
  {
    id: "p-deshawn",
    slug: "deshawn-carter",
    name: "DeShawn Carter",
    city: "Chicago", state: "IL",
    homeGymId: "g-north-star",
    disciplines: ["striking"], primaryDiscipline: "striking",
    rank: "Boxing — Golden Gloves quarterfinalist",
    yearsTraining: 7, weightKg: 68,
    availability: ["Evening"], weekdays: ["Wed", "Fri"],
    lookingFor: ["Comp prep"],
    bio: "Slick style, high volume, honest pressure. Want sparring partners who can cut off the ring. In exchange I hold pads like my paycheck depends on it.",
    lastActiveDays: 3, verified: false,
  },
  {
    id: "p-petra",
    slug: "petra-novak",
    name: "Petra Novak",
    city: "Denver", state: "CO",
    homeGymId: "g-boiler",
    disciplines: ["wrestling", "nogi"], primaryDiscipline: "wrestling",
    rank: "Freestyle wrestler, 12 years",
    yearsTraining: 12, weightKg: 65,
    availability: ["Morning"], weekdays: ["Mon", "Thu", "Sun"],
    lookingFor: ["Open mat", "Drilling"],
    bio: "Czech junior national team back in the day, now coaching. Will drill singles and front headlocks for hours. Also down to just do cardio and complain.",
    lastActiveDays: 1, verified: true,
  },
  {
    id: "p-leo",
    slug: "leo-gutierrez",
    name: "Leo Gutiérrez",
    city: "Miami", state: "FL",
    homeGymId: "g-golden-hour",
    disciplines: ["striking", "mma"], primaryDiscipline: "striking",
    rank: "Muay Thai — 11 amateur bouts",
    yearsTraining: 6, weightKg: 70,
    availability: ["Midday", "Evening"], weekdays: ["Tue", "Sat"],
    lookingFor: ["Open mat", "Comp prep"],
    bio: "Clinch rat. If you want to get better at inside position, I'll throw you around gently for an hour. Looking for leg-kick-check partners who keep it technical.",
    lastActiveDays: 0, verified: true,
  },
  {
    id: "p-hana",
    slug: "hana-sato",
    name: "Hana Sato",
    city: "Portland", state: "OR",
    homeGymId: "g-flatline",
    disciplines: ["bjj", "nogi"], primaryDiscipline: "bjj",
    rank: "BJJ brown belt", beltColor: "#78350F", stripes: 2,
    yearsTraining: 9, weightKg: 66,
    availability: ["Morning", "Evening"], weekdays: ["Mon", "Wed", "Fri"],
    lookingFor: ["Comp prep", "Open mat"],
    bio: "ADCC trials season. Need partners who know modern leglock defense and won't ego-roll at 6 am. I keep a notebook; drone footage of rounds available on request.",
    lastActiveDays: 0, verified: true,
  },
  {
    id: "p-tom",
    slug: "tom-okafor",
    name: "Tom Okafor",
    city: "New York", state: "NY",
    homeGymId: "g-anchor-arm",
    disciplines: ["judo", "bjj"], primaryDiscipline: "judo",
    rank: "Judo brown / BJJ blue", beltColor: "#78350F",
    yearsTraining: 8, weightKg: 81,
    availability: ["Evening"], weekdays: ["Tue", "Thu"],
    lookingFor: ["Open mat"],
    bio: "Big man, soft grips, good ukemi. Translating judo standing into BJJ-friendly takedowns — let's trade sets at open mat. Always show up on time.",
    lastActiveDays: 5, verified: false,
  },
  {
    id: "p-grace",
    slug: "grace-lindqvist",
    name: "Grace Lindqvist",
    city: "Los Angeles", state: "CA",
    homeGymId: "g-clash",
    disciplines: ["wrestling", "nogi"], primaryDiscipline: "wrestling",
    rank: "Freestyle wrestler, 6 years",
    yearsTraining: 6, weightKg: 57,
    availability: ["Morning"], weekdays: ["Wed", "Sat"],
    lookingFor: ["Drilling", "Beginner friendly"],
    bio: "Small, relentless, technical. Perfect partner if you actually want to drill and not roll. Currently rebuilding my shot under knee rehab constraints — low impact only.",
    lastActiveDays: 2, verified: true,
  },
  {
    id: "p-rafael",
    slug: "rafael-duarte",
    name: "Rafael Duarte",
    city: "Austin", state: "TX",
    homeGymId: "g-cinder",
    disciplines: ["bjj", "mma"], primaryDiscipline: "bjj",
    rank: "BJJ white belt", beltColor: "#D6D3D1", stripes: 2,
    yearsTraining: 1, weightKg: 84,
    availability: ["Midday"], weekdays: ["Mon", "Fri"],
    lookingFor: ["Beginner friendly", "Open mat"],
    bio: "Eight months in, ex-rugby, strong as an ox, clueless as a goldfish. Very safe partner, zero ego, will tap early and ask questions loudly. Buy-the-acai bowl kind of gratitude.",
    lastActiveDays: 1, verified: false,
  },
  {
    id: "p-mei",
    slug: "mei-chen",
    name: "Mei Chen",
    city: "San Francisco", state: "CA",
    homeGymId: "g-cerro",
    disciplines: ["mma", "striking"], primaryDiscipline: "mma",
    rank: "Amateur MMA (3–1, flyweight)",
    yearsTraining: 4, weightKg: 61,
    availability: ["Evening"], weekdays: ["Wed", "Sun"],
    lookingFor: ["Comp prep", "Drilling"],
    bio: "Switch stance, cardio for days. Need wall-wrestling partners and anyone who can mimic a grappler-heavy opponent. Film review after rounds if you want it.",
    lastActiveDays: 0, verified: true,
  },
];

export const OPEN_MATS: OpenMat[] = [
  { id: "m-1", gymId: "g-clash", title: "Saturday open mat — gi", discipline: "bjj", weekday: 6, weekOffset: 0, start: "10:00", end: "12:00", level: "All levels", fee: 15, capacity: 40, attendeesBase: 22, womenOnly: false, hostName: "Renan Vasconcelos", hostContact: "frontdesk@clashgrappling.example.com", visitorRequirements: "Gi, any color · mouthguard recommended", notes: "Rounds run 7 minutes, last 30 min is no-points flow. Loaner gis up front." },
  { id: "m-2", gymId: "g-flatline", title: "No-gi Saturday", discipline: "nogi", weekday: 6, weekOffset: 0, start: "13:00", end: "15:00", level: "All levels", fee: 15, capacity: 30, attendeesBase: 18, womenOnly: false, hostName: "Bea Fontoura", hostContact: "frontdesk@flatlinebjj.example.com", visitorRequirements: "Rashguard, no pockets · heel hooks by agreement", notes: "Leglock-friendly room. Heel hooks only if both partners agree pre-round." },
  { id: "m-3", gymId: "g-nine-clouds", title: "Women's open mat", discipline: "bjj", weekday: 6, weekOffset: 0, start: "11:00", end: "12:30", level: "All levels", fee: 10, capacity: 24, attendeesBase: 15, womenOnly: true, hostName: "Dana Reyes", hostContact: "front@ninecloudsbjj.example.com", visitorRequirements: "Women only · gi, any academy welcome", notes: "Hosted by Coach Dana. All ranks, all academies — bring a friend new to the sport if you like." },
  { id: "m-4", gymId: "g-harbor", title: "Judo open randori", discipline: "judo", weekday: 6, weekOffset: 0, start: "12:00", end: "14:00", level: "All levels", fee: 10, capacity: 36, attendeesBase: 12, womenOnly: false, hostName: "Akira Onishi", hostContact: "info@harborjudo.example.com", visitorRequirements: "Judogi, any color · take ukemi seriously", notes: "Standing and ne-waza rounds. Nage-komi mats open the second hour." },
  { id: "m-5", gymId: "g-golden-hour", title: "Open mat + pads", discipline: "striking", weekday: 0, weekOffset: 0, start: "10:30", end: "12:30", level: "All levels", fee: 20, capacity: 28, attendeesBase: 14, womenOnly: false, hostName: "Kwan Sitmonchai", hostContact: "gym@goldenhourmt.example.com", visitorRequirements: "Wraps mandatory · shin guards for sparring", notes: "Rings and bag line open. Light technical sparring only — no hard shots without corner approval." },
  { id: "m-6", gymId: "g-anchor-arm", title: "Sunday scramble", discipline: "bjj", weekday: 0, weekOffset: 0, start: "11:00", end: "13:00", level: "All levels", fee: 25, capacity: 32, attendeesBase: 21, womenOnly: false, hostName: "Levan Kiknadze", hostContact: "front@anchorandarm.example.com", visitorRequirements: "Email before first visit · gi or rashguard", notes: "Gi in the big room, no-gi on the flexi-roll. Grip-fighting circle at 12:30." },
  { id: "m-7", gymId: "g-cinder", title: "MMA open mat", discipline: "mma", weekday: 6, weekOffset: 0, start: "12:00", end: "14:00", level: "Competition", fee: 20, capacity: 24, attendeesBase: 19, womenOnly: false, hostName: "Val Ospina", hostContact: "mat@cindercombat.example.com", visitorRequirements: "4 oz gloves + shin guards for sparring", notes: "Cage wall reserved on the hour. 4 oz gloves and shin guards required for sparring rounds." },
  { id: "m-8", gymId: "g-clash", title: "Friday shark tank", discipline: "bjj", weekday: 5, weekOffset: 0, start: "19:00", end: "21:00", level: "Competition", fee: 15, capacity: 36, attendeesBase: 27, womenOnly: false, hostName: "April Duarte", hostContact: "frontdesk@clashgrappling.example.com", visitorRequirements: "Six+ months experience recommended", notes: "King-of-the-mat format. Not recommended for under six months of training." },
  { id: "m-9", gymId: "g-nine-clouds", title: "Sunday open mat — gi", discipline: "bjj", weekday: 0, weekOffset: 0, start: "10:00", end: "12:00", level: "All levels", fee: 10, capacity: 40, attendeesBase: 16, womenOnly: false, hostName: "Marcelo Assunção", hostContact: "front@ninecloudsbjj.example.com", visitorRequirements: "Gi, any color · welcoming to visitors", notes: "Slow Sunday vibe — drilling corners welcome if rolling isn't your thing." },
  { id: "m-10", gymId: "g-north-star", title: "Open ring + bags", discipline: "striking", weekday: 6, weekOffset: 0, start: "09:00", end: "11:00", level: "All levels", fee: 15, capacity: 30, attendeesBase: 11, womenOnly: false, hostName: "Eddie Kaczmarek", hostContact: "ring@northstarboxing.example.com", visitorRequirements: "Wraps + gloves required", notes: "Two rings on rotation, 10-bag line. Coaches hold mitts by request." },
  { id: "m-11", gymId: "g-boiler", title: "Sunday wrestling room", discipline: "wrestling", weekday: 0, weekOffset: 0, start: "09:30", end: "11:30", level: "All levels", fee: 10, capacity: 28, attendeesBase: 9, womenOnly: false, hostName: "Dan Petrosyan", hostContact: "coach@boilerroom.example.com", visitorRequirements: "Wrestling shoes only on the mat", notes: "Live goes by weight class, drilling stations on the second mat. Bring wrestling shoes." },
  { id: "m-12", gymId: "g-cerro", title: "MMA + striking open mat", discipline: "mma", weekday: 6, weekOffset: 0, start: "10:00", end: "12:00", level: "All levels", fee: 20, capacity: 26, attendeesBase: 13, womenOnly: false, hostName: "Pilár Andrade", hostContact: "sparr@cerrostriking.example.com", visitorRequirements: "Sparring with coach sign-off", notes: "Wall rounds and pad stations. Sparring only with coach sign-off." },
  { id: "m-13", gymId: "g-nine-clouds", title: "Women's open mat", discipline: "bjj", weekday: 6, weekOffset: 1, start: "11:00", end: "12:30", level: "All levels", fee: 10, capacity: 24, attendeesBase: 8, womenOnly: true, hostName: "Dana Reyes", hostContact: "front@ninecloudsbjj.example.com", visitorRequirements: "Women only · gi, any academy welcome", notes: "Second Saturday of the month hosted by brown belt guests. All academies welcome." },
  { id: "m-14", gymId: "g-clash", title: "Saturday open mat — gi", discipline: "bjj", weekday: 6, weekOffset: 1, start: "10:00", end: "12:00", level: "All levels", fee: 15, capacity: 40, attendeesBase: 9, womenOnly: false, hostName: "Renan Vasconcelos", hostContact: "frontdesk@clashgrappling.example.com", visitorRequirements: "Gi, any color · mouthguard recommended", notes: "Visitor week roll-in — first week of training is on the house at Clash." },
];

/*
 * Derived directory metadata. Neighborhoods come from the street address so
 * the filter bar has real sub-city areas; `hasOpenMat` / `dropInsWelcome`
 * power the two boolean filters in spec 5.1.
 */
const NEIGHBORHOODS: Record<string, string> = {
  "g-clash": "Eagle Rock",
  "g-nine-clouds": "North Park",
  "g-harbor": "Greenwood",
  "g-boiler": "Sunnyside",
  "g-cinder": "East Austin",
  "g-golden-hour": "Wynwood",
  "g-north-star": "West Town",
  "g-flatline": "Buckman",
  "g-anchor-arm": "Williamsburg",
  "g-cerro": "Mission District",
};

GYMS.forEach((g) => {
  g.neighborhood = NEIGHBORHOODS[g.id] ?? g.city;
  g.hasOpenMat = g.schedule.some((s) => s.openMat);
  g.dropInsWelcome = g.dropIn > 0;
});

export const NEIGHBORHOOD_LIST = [...new Set(GYMS.map((g) => g.neighborhood!))].sort();

// Visitor-friendly badge (admin-set): rooms whose drop-in policy is explicit,
// current, and welcoming to travelers.
const VISITOR_FRIENDLY = new Set(["g-clash", "g-nine-clouds", "g-harbor", "g-cinder", "g-golden-hour", "g-anchor-arm"]);
GYMS.forEach((g) => { g.visitorFriendly = VISITOR_FRIENDLY.has(g.id); });

/* Quick lookup helpers used across list/detail pages. */
export const GYM_BY_ID = new Map(GYMS.map((g) => [g.id, g]));
export const GYM_BY_SLUG = new Map(GYMS.map((g) => [g.slug, g]));
export const PARTNER_BY_SLUG = new Map(PARTNERS.map((p) => [p.slug, p]));

export function gymName(id: string) {
  return GYM_BY_ID.get(id)?.name ?? "Unknown gym";
}
